[package]
name = "serverless-gateway"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.3", features = ["derive"] }
config = "0.14.0"
ethers = "2.0.14"
serde = "1.0.159"
serde_derive = "1.0.193"
serde_json = "1.0.88"
tokio = { version = "1.36.0", features = ["full"] }
